from collections import namedtuple

test_input = """L68
L30
R48
L5
R60
L55
L1
L99
R14
L82"""

Instr = namedtuple("Instr", ["Dir", "Amount"])

def parse_input(s):
    return [Instr(w[0], int(w[1:])) for w in s.splitlines()]

def next_pos_click(pos, instr):
    d = instr.Amount
    if instr.Dir == "L":
        d = -d
    t = pos + d
    clicks = 0
    if t >= 100:
        clicks = t // 100
    elif t <= 0:
        clicks = -t // 100
        if pos > 0:
            clicks += 1
    return t%100, clicks

def run_part1(i):
    pos = 50
    c = 0
    for instr in i:
        pos, _ = next_pos_click(pos, instr)
        if pos == 0:
            c += 1
    print(c)

def run_part2(i):
    pos = 50
    cc = 0
    for instr in i:
        pos, clicks = next_pos_click(pos, instr)
        cc += clicks
    print(cc)

### Generated by start script

def test_part1():
    run_part1(parse_input(test_input))

def part1():
    run_part1(parse_input(open("input.txt").read()))

def test_part2():
    run_part2(parse_input(test_input))

def part2():
    run_part2(parse_input(open("input.txt").read()))

def main():
    print("=== running part 1 test ===")
    test_part1()
    print("=== running part 1 ===")
    part1()
    print("=== running part 2 test ===")
    test_part2()
    print("=== running part 2 ===")
    part2()
    print("=== ===")

if __name__ == "__main__":
    main()
