// DO NOT EDIT: File generated by aoc 2023
package main

import (
	"github.com/adamhicks/adventofcode/2023/day01"
	"github.com/adamhicks/adventofcode/2023/day02"
	"github.com/adamhicks/adventofcode/2023/day03"
	"github.com/adamhicks/adventofcode/2023/day04"
	"github.com/adamhicks/adventofcode/2023/day05"
	"github.com/adamhicks/adventofcode/2023/day06"
	"github.com/adamhicks/adventofcode/2023/day07"
	"github.com/adamhicks/adventofcode/2023/day08"
	"github.com/adamhicks/adventofcode/2023/day09"
	"github.com/adamhicks/adventofcode/2023/day10"
	"github.com/adamhicks/adventofcode/2023/day11"
	"github.com/adamhicks/adventofcode/2023/day12"
	"github.com/adamhicks/adventofcode/2023/day13"
	"github.com/adamhicks/adventofcode/2023/day14"
	"github.com/adamhicks/adventofcode/2023/day15"
	"github.com/adamhicks/adventofcode/2023/day16"
	"github.com/adamhicks/adventofcode/2023/day17"
	"github.com/adamhicks/adventofcode/2023/day18"
	"github.com/adamhicks/adventofcode/2023/day19"
	"github.com/adamhicks/adventofcode/2023/day20"
	"github.com/adamhicks/adventofcode/2023/day21"
	"github.com/adamhicks/adventofcode/2023/day22"
	"github.com/adamhicks/adventofcode/2023/day23"
	"github.com/adamhicks/adventofcode/2023/day25"
)

var daySolutions = map[int]DaySolution{
	1: day01.Solution{},
	2: day02.Solution{},
	3: day03.Solution{},
	4: day04.Solution{},
	5: day05.Solution{},
	6: day06.Solution{},
	7: day07.Solution{},
	8: day08.Solution{},
	9: day09.Solution{},
	10: day10.Solution{},
	11: day11.Solution{},
	12: day12.Solution{},
	13: day13.Solution{},
	14: day14.Solution{},
	15: day15.Solution{},
	16: day16.Solution{},
	17: day17.Solution{},
	18: day18.Solution{},
	19: day19.Solution{},
	20: day20.Solution{},
	21: day21.Solution{},
	22: day22.Solution{},
	23: day23.Solution{},
	25: day25.Solution{},
}
