// DO NOT EDIT: File generated by aoc 2023
package main

import (
	"github.com/adamhicks/adventofcode/2023/day01"
	"github.com/adamhicks/adventofcode/2023/day02"
	"github.com/adamhicks/adventofcode/2023/day03"
	"github.com/adamhicks/adventofcode/2023/day04"
	"github.com/adamhicks/adventofcode/2023/day05"
	"github.com/adamhicks/adventofcode/2023/day06"
	"github.com/adamhicks/adventofcode/2023/day07"
)

var daySolutions = map[int]DaySolution{
	1: day01.Solution{},
	2: day02.Solution{},
	3: day03.Solution{},
	4: day04.Solution{},
	5: day05.Solution{},
	6: day06.Solution{},
	7: day07.Solution{},
}
