from functools import reduce
from itertools import pairwise

test_input = """aaa: you hhh
you: bbb ccc
bbb: ddd eee
ccc: ddd eee fff
ddd: ggg
eee: out
fff: out
ggg: out
hhh: ccc fff iii
iii: out
"""

test_input_2 = """svr: aaa bbb
aaa: fft
fft: ccc
bbb: tty
tty: ccc
ccc: ddd eee
ddd: hub
hub: fff
eee: dac
dac: fff
fff: ggg hhh
ggg: out
hhh: out
"""

def parse_input(s):
    d = dict()
    for l in s.splitlines():
        f, rest = l.split(": ")
        d[f] = rest.split()
    return d

def dfs_routes(nodes, n, end, mem):
    if n == end:
        return 1
    elif n in mem:
        return mem[n]

    tot = sum(dfs_routes(nodes, nxt, end, mem) for nxt in nodes.get(n,[]))
    mem[n] = tot
    return tot

def run_part1(i):
    print(dfs_routes(i, "you", "out", dict()))

def product(i):
    return reduce(lambda x, y: x*y, i)

def run_part2(i):
    routes = [
        ("svr", "fft", "dac", "out"),
        ("svr", "dac", "fft", "out"),
    ]
    print(sum(product(dfs_routes(i, a, b, dict()) for a, b in pairwise(r)) for r in routes))

### Generated by start script

def test_part1():
    run_part1(parse_input(test_input))

def part1():
    run_part1(parse_input(open("input.txt").read()))

def test_part2():
    run_part2(parse_input(test_input_2))

def part2():
    run_part2(parse_input(open("input.txt").read()))

def main():
    print("=== running part 1 test ===")
    test_part1()
    print("=== running part 1 ===")
    part1()
    print("=== running part 2 test ===")
    test_part2()
    print("=== running part 2 ===")
    part2()
    print("=== ===")

if __name__ == "__main__":
    main()
