#!/bin/zsh

DAY_DIR=$1

if [ -d "$DAY_DIR" ]; then 
    echo "directory $DAY_DIR already exists"
    exit 1
fi

cp -R day00 $DAY_DIR

echo "to run tests: './aoc-test $DAY_DIR'"
echo "to run with input './aoc $DAY_DIR'"
