import re
from functools import reduce

test_input = """123 328  51 64 
 45 64  387 23 
  6 98  215 314
*   +   *   +  
"""

def parse_input(s):
    all = [re.split("\s+", l.strip()) for l in s.splitlines()]
    nums = [tuple(map(int, l)) for l in all[:-1]]
    return nums, all[-1]

def tot(nums, op):
    if op == '*':
        return reduce(lambda x, y: x*y, nums)
    elif op == '+':
        return sum(nums)
    else:
        raise ValueError("invalid op: " + op)

def pivot(its):
    return tuple(tuple(r[col] for r in its) for col in range(len(its[0])))

def run_part1(i):
    nums, ops = i
    nums = pivot(nums)
    print(sum(tot(n, ops[idx]) for idx, n in enumerate(nums)))

def parse_input2(s):
    lines = s.splitlines()
    ops = re.split("\s+", lines[-1].strip())

    nums, this = [], []
    for n in pivot(lines[:-1]):
        v = ''.join(n).strip()
        if not v:
            nums.append(this)
            this = []
        else:
            this.append(int(v))
    if this:
        nums.append(this)    
    return nums, ops

def run_part2(i):
    nums, ops = i
    print(sum(tot(n, ops[idx]) for idx, n in enumerate(nums)))

### Generated by start script

def test_part1():
    run_part1(parse_input(test_input))

def part1():
    run_part1(parse_input(open("input.txt").read()))

def test_part2():
    run_part2(parse_input2(test_input))

def part2():
    run_part2(parse_input2(open("input.txt").read()))

def main():
    print("=== running part 1 test ===")
    test_part1()
    print("=== running part 1 ===")
    part1()
    print("=== running part 2 test ===")
    test_part2()
    print("=== running part 2 ===")
    part2()
    print("=== ===")

if __name__ == "__main__":
    main()
