test_input = """987654321111111
811111111111119
234234234234278
818181911112111
"""

def parse_input(s):
    return s.strip().splitlines()

def max_leftmost(l):
    return max(list(enumerate(int(c) for c in l)), key=lambda x: x[1])

def jolts(l, n):
    i, r = 0, 0
    for j in range(n):
        to = len(l) - (n - j - 1)
        ii, v = max_leftmost(l[i:to])
        r = r*10 + v
        i += ii+1
    return r

def run_part1(i):
    print(sum(jolts(l, 2) for l in i))

def run_part2(i):
    print(sum(jolts(l, 12) for l in i))

### Generated by start script

def test_part1():
    run_part1(parse_input(test_input))

def part1():
    run_part1(parse_input(open("input.txt").read()))

def test_part2():
    run_part2(parse_input(test_input))

def part2():
    run_part2(parse_input(open("input.txt").read()))

def main():
    print("=== running part 1 test ===")
    test_part1()
    print("=== running part 1 ===")
    part1()
    print("=== running part 2 test ===")
    test_part2()
    print("=== running part 2 ===")
    part2()
    print("=== ===")

if __name__ == "__main__":
    main()
