from collections import namedtuple
from math import sqrt

test_input = """162,817,812
57,618,57
906,360,560
592,479,940
352,342,300
466,668,158
542,29,236
431,825,988
739,650,466
52,470,668
216,146,977
819,987,18
117,168,530
805,96,715
346,949,466
970,615,88
941,993,340
862,61,35
984,92,344
425,690,689
"""

def parse_input(s):
    return tuple(Coord(*map(int, l.split(","))) for l in s.splitlines())

Coord = namedtuple("Coord", ["x", "y", "z"])

def sq(x):
    return x * x

def distance(a, b):
    return sqrt(sq(b.x - a.x) + sq(b.y - a.y) + sq(b.z - a.z))

def link_next(a, b, circuits):
    sa, sb = circuits.get(a), circuits.get(b)
    if sa and sb:
        sa |= sb
        for k in sb:
            circuits[k] = sa
    elif sa:
        sa.add(b)
        circuits[b] = sa
    elif sb:
        sb.add(a)
        circuits[a] = sb
    else:
        ss = {a, b}
        circuits[a] = ss
        circuits[b] = ss

def run_part1(i, max):
    dists = [(distance(a, b), a, b) for idx, a in enumerate(i) for b in i[idx+1:]]
    dists = sorted(dists, key=lambda d: d[0])

    circuits = dict()
    for d in dists[:max]:
        _, a, b = d
        link_next(a, b, circuits)

    lens = sorted(list({len(c) for c in circuits.values()}), reverse=True)
    print(lens[0] * lens[1] * lens[2])

def run_part2(i):
    dists = [(distance(a, b), a, b) for idx, a in enumerate(i) for b in i[idx+1:]]
    dists = sorted(dists, key=lambda d: d[0])

    circuits = dict()
    for d in dists:
        _, a, b = d
        link_next(a, b, circuits)
        c = list(circuits.values())[0]
        if (len(c) == len(i)):
            print(a.x * b.x)
            return


### Generated by start script

def test_part1():
    run_part1(parse_input(test_input), 10)

def part1():
    run_part1(parse_input(open("input.txt").read()), 1000)

def test_part2():
    run_part2(parse_input(test_input))

def part2():
    run_part2(parse_input(open("input.txt").read()))

def main():
    print("=== running part 1 test ===")
    test_part1()
    print("=== running part 1 ===")
    part1()
    print("=== running part 2 test ===")
    test_part2()
    print("=== running part 2 ===")
    part2()
    print("=== ===")

if __name__ == "__main__":
    main()
