test_input = """11-22,95-115,998-1012,1188511880-1188511890,222220-222224,
1698522-1698528,446443-446449,38593856-38593862,565653-565659,
824824821-824824827,2121212118-2121212124
"""

def parse_input(s):
    return [list(map(int, r.split("-"))) for r in s.split(",")]

def is_repeated(s, ss):
    l = len(ss)
    return all(s[l*j:l*j+l] == ss for j in range(1, len(s)//l))

def is_repeated_twice(i):
    s = str(i)
    if len(s)%2 != 0:
        return False
    ss = s[:len(s)//2]
    return is_repeated(s, ss)

def is_repeated_any(i):
    s = str(i)
    for l in range(1, (len(s)//2) + 1):
        if len(s)%l != 0:
            continue
        ss = s[:l]
        if is_repeated(s, ss):
            return True
    return False

def run_part1(i):
    print( sum(x for p in i for x in range(p[0], p[1]+1) if is_repeated_twice(x)))

def run_part2(i):
    print( sum(x for p in i for x in range(p[0], p[1]+1) if is_repeated_any(x)))

### Generated by start script

def test_part1():
    run_part1(parse_input(test_input))

def part1():
    run_part1(parse_input(open("input.txt").read()))

def test_part2():
    run_part2(parse_input(test_input))

def part2():
    run_part2(parse_input(open("input.txt").read()))

def main():
    print("=== running part 1 test ===")
    test_part1()
    print("=== running part 1 ===")
    part1()
    print("=== running part 2 test ===")
    test_part2()
    print("=== running part 2 ===")
    part2()
    print("=== ===")

if __name__ == "__main__":
    main()
