from collections import namedtuple

test_input = """0:
###
##.
##.

1:
###
##.
.##

2:
.##
###
##.

3:
##.
###
##.

4:
###
#..
###

5:
###
.#.
###

4x4: 0 0 0 0 2 0
12x5: 1 0 1 0 2 2
12x5: 1 0 1 0 3 2
"""

Coord = namedtuple("Coord", ["x", "y"])
Space = namedtuple("Space", ["size", "needs"])

def parse_shape(p):
    return [Coord(x, y)
        for y, l in enumerate(p[1:])
        for x, c in enumerate(l) if c == "#"
    ]

def parse_space(s):
    dim, l = s.split(": ")
    return Space(
        size=Coord(*map(int, dim.split("x"))),
        needs=tuple(map(int, l.split(" "))),
    )

def parse_input(s):
    parts = s.split("\n\n")
    shapes = tuple(parse_shape(p.splitlines()) for p in parts[:-1])
    spaces = tuple(parse_space(p) for p in parts[-1].splitlines())
    return shapes, spaces

def run_part1(i):
    shapes, spaces = i
    print(sum(
        1 for sp in spaces 
        if sp.size.x * sp.size.y >= sum(
            v * len(shapes[i]) for i, v in enumerate(sp.needs)
        )
    ))

def run_part2(i):
    pass

### Generated by start script

def test_part1():
    run_part1(parse_input(test_input))

def part1():
    run_part1(parse_input(open("input.txt").read()))

def test_part2():
    run_part2(parse_input(test_input))

def part2():
    run_part2(parse_input(open("input.txt").read()))

def main():
    print("=== running part 1 test ===")
    test_part1()
    print("=== running part 1 ===")
    part1()
    print("=== running part 2 test ===")
    test_part2()
    print("=== running part 2 ===")
    part2()
    print("=== ===")

if __name__ == "__main__":
    main()
