from collections import defaultdict

test_input = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""

def parse_input(s):
    lines = s.splitlines()
    start = next(i for i, v in enumerate(lines[0]) if v == 'S')
    splits = tuple(set(i for i, c in enumerate(l) if c == '^') for l in lines[1:])
    return start, splits

def run_part1(i):
    start, splits = i
    beams = {start}
    c = 0
    for row in splits:
        next_beams = beams.copy()
        for i in row:
            if i in beams:
                next_beams.add(i-1)
                next_beams.add(i+1)
                c += 1
        next_beams -= row
        beams = next_beams
    print(c)

def run_part2(i):
    start, splits = i
    beams = {start: 1}
    for row in splits:
        next_beams = defaultdict(int)
        for b, v in beams.items():
            if b in row:
                next_beams[b-1] += v
                next_beams[b+1] += v
            else:
                next_beams[b] += v
        beams = next_beams
    print(sum(beams.values()))

### Generated by start script

def test_part1():
    run_part1(parse_input(test_input))

def part1():
    run_part1(parse_input(open("input.txt").read()))

def test_part2():
    run_part2(parse_input(test_input))

def part2():
    run_part2(parse_input(open("input.txt").read()))

def main():
    print("=== running part 1 test ===")
    test_part1()
    print("=== running part 1 ===")
    part1()
    print("=== running part 2 test ===")
    test_part2()
    print("=== running part 2 ===")
    part2()
    print("=== ===")

if __name__ == "__main__":
    main()
