test_input = """3-5
10-14
16-20
12-18

1
5
8
11
17
32
"""

def parse_input(s):
    p1, p2 = s.split("\n\n")
    ranges = [tuple(map(int, p.split("-"))) for p in p1.splitlines()]
    ingredients = tuple(map(int, p2.splitlines()))
    return ranges, ingredients

def run_part1(i):
    rng, ing = i
    print(sum(1 for ing_id in ing if any(r for r in rng if r[0] <= ing_id <= r[1])))

def run_part2(i):
    rng, ing = i
    merged = []
    prev = None
    for r in sorted(rng):
        if prev is not None:
            if prev[1] >= r[0]:
                prev = (prev[0], max(prev[1], r[1]))
                continue
            else:
                merged.append(prev)
        prev = r
    if prev is not None:
        merged.append(prev)

    print(sum(r[1]-r[0]+1 for r in merged))

### Generated by start script

def test_part1():
    run_part1(parse_input(test_input))

def part1():
    run_part1(parse_input(open("input.txt").read()))

def test_part2():
    run_part2(parse_input(test_input))

def part2():
    run_part2(parse_input(open("input.txt").read()))

def main():
    print("=== running part 1 test ===")
    test_part1()
    print("=== running part 1 ===")
    part1()
    print("=== running part 2 test ===")
    test_part2()
    print("=== running part 2 ===")
    part2()
    print("=== ===")

if __name__ == "__main__":
    main()
